AWS_RDS_HOST = 'mymedirecords.cbs8imeeg5j7.us-east-1.rds.amazonaws.com'
AWS_DB_NAME = "mymedirecords"
AWS_DB_USER_NAME = "postgres"
AWS_DB_PASS = "admin1234"
AWS_DB_PORT = 5432

AWS_access_key_id = "AKIAS3DOCB27ZUSB7EWH"
AWS_secret_access_key = "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"
AWS_bucket_name = "mymedirecords"

OPEN_AI_API_KEY = "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"

REPORT_PATH = "data/reports"
EXTRACTED_PATH = "data/extracted_reports"

TEST_NAME = ["Absolute neutrophil count", "Activated partial thromboplastin time", "Bleeding time", "Erythrocyte count",
              "Erythrocyte sedimentation rate", "Erythropoietin", "D-Dimer", "Ferritin, serum", "Haptoglobin, serum", "Hematocrit",
              "Hemoglobin, blood", "Leukocyte alkaline phosphatase", "Leukocyte count", "Mean corpuscular hemoglobin", "Mean corpuscular hemoglobin concentration",
              "Mean corpuscular volume", "Platelet count", "Prothrombin time", "Reticulocyte count", "Protein, serum Total", "Albumin", "Globulins, total",
              "Alkaline phosphatase, serum", "Alpha-Fetoprotein, serum", "Aminotransferase, alanine", "Aminotransferase, aspartate", "Ammonia, plasma",
              "Amylase, serum", "Bicarbonate, serum", "Bilirubin, serum Total", "Bilirubin, serum Direct", "γ-Glutamyltransferase, serum", "Fibrinogen, plasma",
              "Lactic acid, venous blood", "Lipase, serum", "Magnesium, serum", "Tacrolimus level", "pH", "Pco2", "Po2", "Oxygen saturation", "Blood urea nitrogen",
              "C-reactive protein", "Calcium, serum", "Carbon dioxide, serum", "Chloride, serum", "Total Cholesterol", "LDL Cholesterol", "HDL Cholesterol",
              "Triglycerides", "Complement, serum C3", "Complement, serum Total, CH50", "Creatine kinase, serum", "Creatinine, serum", "Electrolytes, serum Sodium",
              "Electrolytes, serum Potassium", "Electrolytes, serum Chloride", "Electrolytes, serum Bicarbonate", "Folate, red cell", "Folate, serum", "Glucose, plasma",
              "Homocysteine, plasma", "Immunoglobulins", "IgG", "IgA", "IgM", "IgD", "IgE", "Iron studies: Ferritin, serum", "Iron, serum",
              "Iron-binding capacity, total, serum", "Lactate dehydrogenase, serum", "Lipase, serum", "Methylmalonic acid, serum", "Osmolality, plasma",
              "Phosphatase, alkaline, serum", "Phosphorus, serum", "Potassium, serum", "Prostate-specific antigen, serum", "Protein, serum Total", "Albumin",
              "Globulins, total", "Rheumatoid factor", "Sodium, serum", "Transferrin saturation", "Troponins, serum Troponin I", "Troponins, serum Troponin T",
              "Creatine kinase CK", "Creatine kinase MB CKMB", "B type natriuretic peptide BNP", "Urea nitrogen, blood", "Uric acid, serum", "Thyroid iodine uptake",
              "Thyroid-stimulating hormone TSH", "Thyroxine T4", "Free T4 index", "Triiodothyronine T3", "Adrenocorticotropic hormone ACTH", "Aldosterone, serum Supine",
              "Aldosterone, serum Standing", "Aldosterone, urine", "Catecholamines Epinephrine", "Catecholamines Norepinephrine", "Catecholamines, 24-hour, urine",
              "Cortisol, free, urine", "Dehydroepiandrosterone sulfate DHEA", "Estradiol, serum", "Follicle-stimulating hormone, serum", "Growth hormone, plasma",
              "Luteinizing hormone, serum", "Metanephrine, urine", "Parathyroid hormone, serum", "Progesterone, blood", "Prolactin, serum", "Testosterone, serum",
              "Urea nitrogen, blood", "Urine Albumin-creatinine ratio", "Glomerular filtration rate GFR", "5-Hydroxyindoleacetic acid 5-HIAA", "Urine Protein–creatinine ratio",
              "Sodium urine", "Uric acid urine", "Calcium urine", "Gastrin, serum", "Stool fat", "Stool weight", "Forced expiratory volume in 1 second FEV1",
              "Forced vital capacity FVC", "Cerebrospinal Fluid Cell count", "Cerebrospinal Fluid Glucose", "Cerebrospinal Fluid Protein", "Vitamin B12, serum",
              "Vitamin D 1,25-dihydroxy", "Vitamin D 25-hydroxy", "Alpha fetoprotein", "Beta human chorionic gonadotropin HCG", "CA19.9", "Carcinoembryonic antigen CEA",
              "Prostatic acid phosphatase PAP", "Prostate-specific antigen PSA", "Alpha 1-antitrypsin", "Angiotensin-converting enzyme", "D-dimer",
              "Lactate dehydrogenase LDH", "Lead", "Cardiac index", "Left ventricular ejection fraction", "Pressures Pulmonary artery",
              "Pressures Pulmonary capillary wedge", "Pressures Right atrium", "Pressures Right ventricle"]


test_output = '''"TestResult": {
"PersonalDetails": {"Name": "name", "ReportDate":"DD/MM/YYYY", "DoctorName": "doctor_name"},
    "Absolute neutrophil count": {"testValue": "TBD", "valueStatus": "normal"},
    "Activated partial thromboplastin time": {"testValue": "TBD", "valueStatus": "high"},
    "Bleeding time": {"testValue": "TBD", "valueStatus": "normal"},
    "Erythrocyte count": {"testValue": "TBD", "valueStatus": "normal"},
    "Erythrocyte sedimentation rate": {"testValue": "TBD", "valueStatus": "low"},
    "Erythropoietin": {"testValue": "TBD", "valueStatus": "normal"},
    "D-Dimer": {"testValue": "TBD", "valueStatus": "normal"},
    "Ferritin, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Haptoglobin, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Hematocrit": {"testValue": "TBD", "valueStatus": "normal"},
    "Hemoglobin, blood": {"testValue": "TBD", "valueStatus": "normal"},
    "Leukocyte alkaline phosphatase": {"testValue": "TBD", "valueStatus": "normal"},
    "Leukocyte count": {"testValue": "TBD", "valueStatus": "normal"},
    "Mean corpuscular hemoglobin": {"testValue": "TBD", "valueStatus": "normal"},
    "Mean corpuscular hemoglobin concentration": {"testValue": "TBD", "valueStatus": "normal"},
    "Mean corpuscular volume": {"testValue": "TBD", "valueStatus": "normal"},
    "Platelet count": {"testValue": "TBD", "valueStatus": "normal"},
    "Prothrombin time": {"testValue": "TBD", "valueStatus": "normal"},
    "Reticulocyte count": {"testValue": "TBD", "valueStatus": "normal"},
    "Protein, serum Total": {"testValue": "TBD", "valueStatus": "normal"},
    "Albumin": {"testValue": "TBD", "valueStatus": "normal"},
    "Globulins, total": {"testValue": "TBD", "valueStatus": "normal"},
    "Alkaline phosphatase, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Alpha-Fetoprotein, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Aminotransferase, alanine": {"testValue": "TBD", "valueStatus": "normal"},
    "Aminotransferase, aspartate": {"testValue": "TBD", "valueStatus": "normal"},
    "Ammonia, plasma": {"testValue": "TBD", "valueStatus": "normal"},
    "Amylase, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Bicarbonate, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Bilirubin, serum Total": {"testValue": "TBD", "valueStatus": "normal"},
    "Bilirubin, serum Direct": {"testValue": "TBD", "valueStatus": "normal"},
    "γ-Glutamyltransferase, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Fibrinogen, plasma": {"testValue": "TBD", "valueStatus": "normal"},
    "Lactic acid, venous blood": {"testValue": "TBD", "valueStatus": "normal"},
    "Lipase, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Magnesium, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Tacrolimus level": {"testValue": "TBD", "valueStatus": "normal"},
    "pH": {"testValue": "TBD", "valueStatus": "normal"},
    "Pco2": {"testValue": "TBD", "valueStatus": "normal"},
    "Po2": {"testValue": "TBD", "valueStatus": "normal"},
    "Oxygen saturation": {"testValue": "TBD", "valueStatus": "normal"},
    "Blood urea nitrogen": {"testValue": "TBD", "valueStatus": "normal"},
    "C-reactive protein": {"testValue": "TBD", "valueStatus": "normal"},
    "Calcium, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Carbon dioxide, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Chloride, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Total Cholesterol": {"testValue": "TBD", "valueStatus": "normal"},
    "LDL Cholesterol": {"testValue": "TBD", "valueStatus": "normal"},
    "HDL Cholesterol": {"testValue": "TBD", "valueStatus": "normal"},
    "Triglycerides": {"testValue": "TBD", "valueStatus": "normal"},
    "Complement, serum C3": {"testValue": "TBD", "valueStatus": "normal"},
    "Complement, serum Total, CH50": {"testValue": "TBD", "valueStatus": "normal"},
    "Creatine kinase, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Creatinine, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Electrolytes, serum Sodium": {"testValue": "TBD", "valueStatus": "normal"},
    "Electrolytes, serum Potassium": {"testValue": "TBD", "valueStatus": "normal"},
    "Electrolytes, serum Chloride": {"testValue": "TBD", "valueStatus": "normal"},
    "Electrolytes, serum Bicarbonate": {"testValue": "TBD", "valueStatus": "normal"},
    "Folate, red cell": {"testValue": "TBD", "valueStatus": "normal"},
    "Folate, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Glucose, plasma": {"testValue": "TBD", "valueStatus": "normal"},
    "Homocysteine, plasma": {"testValue": "TBD", "valueStatus": "normal"},
    "Immunoglobulins": {"testValue": "TBD", "valueStatus": "normal"},
    "IgG": {"testValue": "TBD", "valueStatus": "normal"},
    "IgA": {"testValue": "TBD", "valueStatus": "normal"},
    "IgM": {"testValue": "TBD", "valueStatus": "normal"},
    "IgD": {"testValue": "TBD", "valueStatus": "normal"},
    "IgE": {"testValue": "TBD", "valueStatus": "normal"},
    "Iron studies: Ferritin, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Iron, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Iron-binding capacity, total, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Lactate dehydrogenase, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Lipase, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Methylmalonic acid, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Osmolality, plasma": {"testValue": "TBD", "valueStatus": "normal"},
    "Phosphatase, alkaline, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Phosphorus, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Potassium, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Prostate-specific antigen, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Protein, serum Total": {"testValue": "TBD", "valueStatus": "normal"},
    "Albumin": {"testValue": "TBD", "valueStatus": "normal"},
    "Globulins, total": {"testValue": "TBD", "valueStatus": "normal"},
    "Rheumatoid factor": {"testValue": "TBD", "valueStatus": "normal"},
    "Sodium, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Transferrin saturation": {"testValue": "TBD", "valueStatus": "normal"},
    "Troponins, serum Troponin I": {"testValue": "TBD", "valueStatus": "normal"},
    "Troponins, serum Troponin T": {"testValue": "TBD", "valueStatus": "normal"},
    "Creatine kinase CK": {"testValue": "TBD", "valueStatus": "normal"},
    "Creatine kinase MB CKMB": {"testValue": "TBD", "valueStatus": "normal"},
    "B type natriuretic peptide BNP": {"testValue": "TBD", "valueStatus": "normal"},
    "Urea nitrogen, blood": {"testValue": "TBD", "valueStatus": "normal"},
    "Uric acid, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Thyroid iodine uptake": {"testValue": "TBD", "valueStatus": "normal"},
    "Thyroid-stimulating hormone TSH": {"testValue": "TBD", "valueStatus": "normal"},
    "Thyroxine T4": {"testValue": "TBD", "valueStatus": "normal"},
    "Free T4 index": {"testValue": "TBD", "valueStatus": "normal"},
    "Triiodothyronine T3": {"testValue": "TBD", "valueStatus": "normal"},
    "Adrenocorticotropic hormone ACTH": {"testValue": "TBD", "valueStatus": "normal"},
    "Aldosterone, serum Supine": {"testValue": "TBD", "valueStatus": "normal"},
    "Aldosterone, serum Standing": {"testValue": "TBD", "valueStatus": "normal"},
    "Aldosterone, urine": {"testValue": "TBD", "valueStatus": "normal"},
    "Catecholamines Epinephrine": {"testValue": "TBD", "valueStatus": "normal"},
    "Catecholamines Norepinephrine": {"testValue": "TBD", "valueStatus": "normal"},
    "Catecholamines, 24-hour, urine": {"testValue": "TBD", "valueStatus": "normal"},
    "Cortisol, free, urine": {"testValue": "TBD", "valueStatus": "normal"},
    "Dehydroepiandrosterone sulfate DHEA": {"testValue": "TBD", "valueStatus": "normal"},
    "Estradiol, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Follicle-stimulating hormone, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Growth hormone, plasma": {"testValue": "TBD", "valueStatus": "normal"},
    "Luteinizing hormone, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Metanephrine, urine": {"testValue": "TBD", "valueStatus": "normal"},
    "Parathyroid hormone, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Progesterone, blood": {"testValue": "TBD", "valueStatus": "normal"},
    "Prolactin, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Testosterone, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Urea nitrogen, blood": {"testValue": "TBD", "valueStatus": "normal"},
    "Urine Albumin-creatinine ratio": {"testValue": "TBD", "valueStatus": "normal"},
    "Glomerular filtration rate GFR": {"testValue": "TBD", "valueStatus": "normal"},
    "5-Hydroxyindoleacetic acid 5-HIAA": {"testValue": "TBD", "valueStatus": "normal"},
    "Urine Protein–creatinine ratio": {"testValue": "TBD", "valueStatus": "normal"},
    "Sodium urine": {"testValue": "TBD", "valueStatus": "normal"},
    "Uric acid urine": {"testValue": "TBD", "valueStatus": "normal"},
    "Calcium urine": {"testValue": "TBD", "valueStatus": "normal"},
    "Gastrin, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Stool fat": {"testValue": "TBD", "valueStatus": "normal"},
    "Stool weight": {"testValue": "TBD", "valueStatus": "normal"},
    "Forced expiratory volume in 1 second FEV1": {"testValue": "TBD", "valueStatus": "normal"},
    "Forced vital capacity FVC": {"testValue": "TBD", "valueStatus": "normal"},
    "Cerebrospinal Fluid Cell count": {"testValue": "TBD", "valueStatus": "normal"},
    "Cerebrospinal Fluid Glucose": {"testValue": "TBD", "valueStatus": "normal"},
    "Cerebrospinal Fluid Protein": {"testValue": "TBD", "valueStatus": "normal"},
    "Vitamin B12, serum": {"testValue": "TBD", "valueStatus": "normal"},
    "Vitamin D 1,25-dihydroxy": {"testValue": "TBD", "valueStatus": "normal"},
    "Vitamin D 25-hydroxy": {"testValue": "TBD", "valueStatus": "normal"},
    "Alpha fetoprotein": {"testValue": "TBD", "valueStatus": "normal"},
    "Beta human chorionic gonadotropin HCG": {"testValue": "TBD", "valueStatus": "normal"},
    "CA19.9": {"testValue": "TBD", "valueStatus": "normal"},
    "Carcinoembryonic antigen CEA": {"testValue": "TBD", "valueStatus": "normal"},
    "Prostatic acid phosphatase PAP": {"testValue": "TBD", "valueStatus": "normal"},
    "Prostate-specific antigen PSA": {"testValue": "TBD", "valueStatus": "normal"},
    "Alpha 1-antitrypsin": {"testValue": "TBD", "valueStatus": "normal"},
    "Angiotensin-converting enzyme": {"testValue": "TBD", "valueStatus": "normal"},
    "D-dimer": {"testValue": "TBD", "valueStatus": "normal"},
    "Lactate dehydrogenase LDH": {"testValue": "TBD", "valueStatus": "normal"},
    "Lead": {"testValue": "TBD", "valueStatus": "normal"},
    "Cardiac index": {"testValue": "TBD", "valueStatus": "normal"},
    "Left ventricular ejection fraction": {"testValue": "TBD", "valueStatus": "normal"},
    "Pressures Pulmonary artery": {"testValue": "TBD", "valueStatus": "normal"},
    "Pressures Pulmonary capillary wedge": {"testValue": "TBD", "valueStatus": "normal"},
    "Pressures Right atrium": {"testValue": "TBD", "valueStatus": "normal"},
    "Pressures Right ventricle": {"testValue": "TBD", "valueStatus": "normal"}
}
'''


result_form = '''"TestResult": {
 "PersonalDetails": {"Name": "name", "ReportDate": "DD/MM/YYYY", "DoctorName": "doctor_name", "Gender":"Male/Female"},
 "Absolute neutrophil count": "TBD",
 "Activated partial thromboplastin time": "TBD",
 "Bleeding time": "TBD",
 "Erythrocyte count": "TBD",
 "Erythrocyte sedimentation rate": "TBD",
 "Erythropoietin": "TBD",
 "D-Dimer": "TBD",
 "Ferritin, serum": "TBD",
 "Haptoglobin, serum": "TBD",
 "Hematocrit": "TBD",
 "Hemoglobin, blood": "TBD",
 "Leukocyte alkaline phosphatase": "TBD",
 "Leukocyte count": "TBD",
 "Mean corpuscular hemoglobin": "TBD",
 "Mean corpuscular hemoglobin concentration": "TBD",
 "Mean corpuscular volume": "TBD",
 "Platelet count": "TBD",
 "Prothrombin time": "TBD",
 "Reticulocyte count": "TBD",
 "Protein, serum Total": "TBD",
 "Albumin": "TBD",
 "Globulins, total": "TBD",
 "Alkaline phosphatase, serum": "TBD",
 "Alpha-Fetoprotein, serum": "TBD",
 "Aminotransferase, alanine": "TBD",
 "Aminotransferase, aspartate": "TBD",
 "Ammonia, plasma": "TBD",
 "Amylase, serum": "TBD",
 "Bicarbonate, serum": "TBD",
 "Bilirubin, serum Total": "TBD",
 "Bilirubin, serum Direct": "TBD",
 "γ-Glutamyltransferase, serum": "TBD",
 "Fibrinogen, plasma": "TBD",
 "Lactic acid, venous blood": "TBD",
 "Lipase, serum": "TBD",
 "Magnesium, serum": "TBD",
 "Tacrolimus level": "TBD",
 "pH": "TBD",
 "Pco2": "TBD",
 "Po2": "TBD",
 "Oxygen saturation": "TBD",
 "Blood urea nitrogen": "TBD",
 "C-reactive protein": "TBD",
 "Calcium, serum": "TBD",
 "Carbon dioxide, serum": "TBD",
 "Chloride, serum": "TBD",
 "Total Cholesterol": "TBD",
 "LDL Cholesterol": "TBD",
 "HDL Cholesterol": "TBD",
 "Triglycerides": "TBD",
 "Complement, serum C3": "TBD",
 "Complement, serum Total, CH50": "TBD",
 "Creatine kinase, serum": "TBD",
 "Creatinine, serum": "TBD",
 "Electrolytes, serum Sodium": "TBD",
 "Electrolytes, serum Potassium": "TBD",
 "Electrolytes, serum Chloride": "TBD",
 "Electrolytes, serum Bicarbonate": "TBD",
 "Folate, red cell": "TBD",
 "Folate, serum": "TBD",
 "Glucose, plasma": "TBD",
 "Homocysteine, plasma": "TBD",
 "Immunoglobulins": "TBD",
 "IgG": "TBD",
 "IgA": "TBD",
 "IgM": "TBD",
 "IgD": "TBD",
 "IgE": "TBD",
 "Iron studies: Ferritin, serum": "TBD",
 "Iron, serum": "TBD",
 "Iron-binding capacity, total, serum": "TBD",
 "Lactate dehydrogenase, serum": "TBD",
 "Methylmalonic acid, serum": "TBD",
 "Osmolality, plasma": "TBD",
 "Phosphatase, alkaline, serum": "TBD",
 "Phosphorus, serum": "TBD",
 "Potassium, serum": "TBD",
 "Prostate-specific antigen, serum": "TBD",
 "Rheumatoid factor": "TBD",
 "Sodium, serum": "TBD",
 "Transferrin saturation": "TBD",
 "Troponins, serum Troponin I": "TBD",
 "Troponins, serum Troponin T": "TBD",
 "Creatine kinase CK": "TBD",
 "Creatine kinase MB CKMB": "TBD",
 "B type natriuretic peptide BNP": "TBD",
 "Urea nitrogen, blood": "TBD",
 "Uric acid, serum": "TBD",
 "Thyroid iodine uptake": "TBD",
 "Thyroid-stimulating hormone TSH": "TBD",
 "Thyroxine T4": "TBD",
 "Free T4 index": "TBD",
 "Triiodothyronine T3": "TBD",
 "Adrenocorticotropic hormone ACTH": "TBD",
 "Aldosterone, serum Supine": "TBD",
 "Aldosterone, serum Standing": "TBD",
 "Aldosterone, urine": "TBD",
 "Catecholamines Epinephrine": "TBD",
 "Catecholamines Norepinephrine": "TBD",
 "Catecholamines, 24-hour, urine": "TBD",
 "Cortisol, free, urine": "TBD",
 "Dehydroepiandrosterone sulfate DHEA": "TBD",
 "Estradiol, serum": "TBD",
 "Follicle-stimulating hormone, serum": "TBD",
 "Growth hormone, plasma": "TBD",
 "Luteinizing hormone, serum": "TBD",
 "Metanephrine, urine": "TBD",
 "Parathyroid hormone, serum": "TBD",
 "Progesterone, blood": "TBD",
 "Prolactin, serum": "TBD",
 "Testosterone, serum": "TBD",
 "Urine Albumin-creatinine ratio": "TBD",
 "Glomerular filtration rate GFR": "TBD",
 "5-Hydroxyindoleacetic acid 5-HIAA": "TBD",
 "Urine Protein–creatinine ratio": "TBD",
 "Sodium urine": "TBD",
 "Uric acid urine": "TBD",
 "Calcium urine": "TBD",
 "Gastrin, serum": "TBD",
 "Stool fat": "TBD",
 "Stool weight": "TBD",
 "Forced expiratory volume in 1 second FEV1": "TBD",
 "Forced vital capacity FVC": "TBD",
 "Cerebrospinal Fluid Cell count": "TBD",
 "Cerebrospinal Fluid Glucose": "TBD",
 "Cerebrospinal Fluid Protein": "TBD",
 "Vitamin B12, serum": "TBD",
 "Vitamin D 1,25-dihydroxy": "TBD",
 "Vitamin D 25-hydroxy": "TBD",
 "Alpha fetoprotein": "TBD",
 "Beta human chorionic gonadotropin HCG": "TBD",
 "CA19.9": "TBD",
 "Carcinoembryonic antigen CEA": "TBD",
 "Prostatic acid phosphatase PAP": "TBD",
 "Prostate-specific antigen PSA": "TBD",
 "Alpha 1-antitrypsin": "TBD",
 "Angiotensin-converting enzyme": "TBD",
 "D-dimer": "TBD",
 "Lactate dehydrogenase LDH": "TBD",
 "Lead": "TBD",
 "Cardiac index": "TBD",
 "Left ventricular ejection fraction": "TBD",
 "Pressures Pulmonary artery": "TBD",
 "Pressures Pulmonary capillary wedge": "TBD",
 "Pressures Right atrium": "TBD",
 "Pressures Right ventricle": "TBD"}
'''


PERSONAL_DETAILS_FORMAT = '''{"PersonalDetails":{"Name":"patient_name",\
"ReportDate":"DD/MM/YYYY", "DoctorName": "doctor_name"}}'''

OUTPUT_FORMAT = '''{"Ammonia, plasma"":{"testValue":"TBD","valueStatus":"normal"},\
"Chloride, serum":{"testValue":"TBD","valueStatus":"normal"},"test_name3":{"testValue":"TBD","valueStatus":"low"},\
"test_name4":{"testValue":"TBD","valueStatus":"high"},...}'''


test_range = {
    "Absolute neutrophil count": {"min": 1780, "max": 5380},
    "Activated partial thromboplastin time": {"min": 25, "max": 35},
    "Bleeding time": {"min": 0, "max": 10},
    "Erythrocyte count": {"min": 4.2, "max": 5.9},
    "Erythrocyte sedimentation rate": {"Male": {"min": 0, "max": 15}, "Female": {"min": 0, "max": 20}},
    "Erythropoietin": {"min": 0, "max": 30},
    "D-Dimer": {"min": 0, "max": 0.5},
    "Ferritin, serum": {"min": 15, "max": 200},
    "Haptoglobin, serum": {"min": 50, "max": 150},
    "Hematocrit": {"Male": {"min": 41, "max": 51}, "Female": {"min": 36, "max": 47}},
    "Hemoglobin, blood": {"Male": {"min": 14, "max": 17}, "Female": {"min": 12, "max": 16}},
    "Leukocyte alkaline phosphatase": {"min": 15, "max": 40},
    "Leukocyte count": {"min": 4000, "max": 10000},
    "Mean corpuscular hemoglobin": {"min": 28, "max": 32},
    "Mean corpuscular hemoglobin concentration": {"min": 32, "max": 36},
    "Mean corpuscular volume": {"min": 80, "max": 100},
    "Platelet count": {"min": 150000, "max": 350000},
    "Prothrombin time": {"min": 11, "max": 13},
    "Reticulocyte count": {"min": 0.5, "max": 1.5},
    "Protein, serum Total": {"min": 6.0, "max": 7.8},
    "Albumin": {"min": 3.5, "max": 5.5},
    "Globulins, total": {"min": 2.5, "max": 3.5},
    "Alkaline phosphatase, serum": {"min": 36, "max": 92},
    "Alpha-Fetoprotein, serum": {"min": 0, "max": 20},
    "Aminotransferase, alanine": {"min": 0, "max": 35},
    "Aminotransferase, aspartate": {"min": 0, "max": 35},
    "Ammonia, plasma": {"min": 40, "max": 80},
    "Amylase, serum": {"min": 0, "max": 130},
    "Bicarbonate, serum": {"min": 23, "max": 28},
    "Bilirubin, serum Total": {"min": 0.3, "max": 1.2},
    "Bilirubin, serum Direct": {"min": 0, "max": 0.3},
    "γ-Glutamyltransferase, serum": {"min": 0, "max": 30},
    "Fibrinogen, plasma": {"min": 150, "max": 350},
    "Lactic acid, venous blood": {"min": 6, "max": 16},
    "Lipase, serum": {"max": 95},
    "Magnesium, serum": {"min": 1.5, "max": 2.4},
    "Tacrolimus level": {"min": 5, "max": 20},
    "pH":{"min":0, "max":0}, "Pco2":{"min":0, "max":0}, "Po2":{"min":0, "max":0}, "Oxygen saturation":{"min":0, "max":0},
    "Blood urea nitrogen": {"min": 8, "max": 20},
    "C-reactive protein": {"min": 0.0, "max": 0.8},
    "Calcium, serum": {"min": 9, "max": 10.5},
    "Carbon dioxide, serum": {},
    "Chloride, serum": {"min": 98, "max": 106},
    "Total Cholesterol": {"min": 150, "max": 199},
    "LDL Cholesterol": {"max": 130},
    "HDL Cholesterol": {"min": 40},
    "Triglycerides": {"min":0, "max":0},
    "Complement, serum C3": {"min": 55, "max": 120},
    "Complement, serum Total, CH50": {"min": 37, "max": 55},
    "Creatine kinase, serum": {"min": 30, "max": 170},
    "Creatinine, serum": {"min": 0.7, "max": 1.3},
    "Electrolytes, serum Sodium": {"min": 136, "max": 145},
    "Electrolytes, serum Potassium": {"min": 3.5, "max": 5.0},
    "Electrolytes, serum Chloride": {"min": 98, "max": 106},
    "Electrolytes, serum Bicarbonate": {"min": 23, "max": 28},
    "Folate, red cell": {"min": 160, "max": 855},
    "Folate, serum": {"min": 2.5, "max": 20},
    "Glucose, plasma": {"min": 70, "max": 100},
    "Homocysteine, plasma": {"Male": {"min": 0.54, "max": 2.16}, "Female": {"min": 0.41, "max": 1.89}},
    "Immunoglobulins": {"min": 2.5, "max": 3.5},
    "IgG": {"min": 640, "max": 1430},
    "IgA": {"min": 70, "max": 300},
    "IgM": {"min": 20, "max": 140},
    "IgD": {"max": 8},
    "IgE": {"min": 0.01, "max": 0.04},
    "Iron studies: Ferritin, serum": {"min": 15, "max": 200},
    "Iron, serum": {"min": 60, "max": 160},
    "Iron-binding capacity, total, serum": {"min": 250, "max": 460},
    "Lactate dehydrogenase, serum": {"min":0, "max":0},
    "Lactate dehydrogenase, serum": {"min": 60, "max": 100},
    "Lactic acid, venous blood": {"min": 6, "max": 16},
    "Lipase, serum": {"min":0, "max": 95},
    "Magnesium, serum": {"min": 1.5, "max": 2.4},
    "Methylmalonic acid, serum": {"min": 150, "max": 370},
    "Osmolality, plasma": {"min": 275, "max": 295},
    "Phosphatase, alkaline, serum": {"min": 36, "max": 92},
    "Phosphorus, serum": {"min": 3, "max": 4.5},
    "Potassium, serum": {"min": 3.5, "max": 5.0},
    "Prostate-specific antigen, serum": {"max": 4},
    "Protein, serum Total": {"min": 6.0, "max": 7.8},
    "Albumin": {"min": 3.5, "max": 5.5},
    "Globulins, total": {"min": 2.5, "max": 3.5},
    "Rheumatoid factor": {"max": 40},
    "Sodium, serum": {"min": 136, "max": 145},
    "Transferrin saturation": {"min": 20, "max": 50},
    "Triglycerides": {"max": 150},
    "Troponins, serum Troponin I": {"max": 0.5},
    "Troponins, serum Troponin T": {"max": 0.10},
    "Creatine kinase": {"min": 25, "max": 200},
    "Creatine kinase MB (CKMB)": {"max": 4},
    "B type natriuretic peptide": {"max": 100},
    "Urea nitrogen, blood": {"min": 8, "max": 20},
    "Uric acid, serum": {"min": 2.5, "max": 8},
    "Vitamin B12, serum": {"min": 200, "max": 800},
    "Vitamin B12, serum": {"min": 200, "max": 800},
    "Adrenocorticotropic hormone (ACTH), serum": {"min": 9, "max": 52},
    "Aldosterone, serum Supine": {"min": 2, "max": 5},
    "Aldosterone, serum Standing": {"min": 7, "max": 20},
    "Aldosterone, urine": {"min": 5, "max": 19},
    "Catecholamines Epinephrine, plasma (supine)": {"max": 75},
    "Catecholamines Norepinephrine, plasma (supine)": {"min": 50, "max": 440},
    "Catecholamines, 24-hour, urine": {"max": 100},
    "Cortisol, free, urine": {"max": 50},
    "Dehydroepiandrosterone sulfate (DHEA), plasma Male": {"min": 1.3, "max": 5.5},
    "Dehydroepiandrosterone sulfate (DHEA), plasma Female": {"min": 0.6, "max": 3.3},
    "Epinephrine, plasma (supine)": {"max": 75},
    "Estradiol, serum Male": {"min": 10, "max": 30},
    "Estradiol, serum Female day 1-10": {"min": 14, "max": 27},
    "Estradiol, serum Female day 11-20": {"min": 14, "max": 54},
    "Estradiol, serum Female day 21-30": {"min": 19, "max": 41},
    "Follicle-stimulating hormone, serum Male (adult)": {"min": 5, "max": 15},
    "Follicle-stimulating hormone, serum Female follicular or luteal phase": {"min": 5, "max": 20},
    "Follicle-stimulating hormone, serum Female midcycle peak": {"min": 30, "max": 50},
    "Follicle-stimulating hormone, serum Female postmenopausal": {"min": 35},
    "Growth hormone, plasma after oral glucose": {"max": 2},
    "Growth hormone, plasma response to provocative stimuli": {"min": 7},
    "Luteinizing hormone, serum Male": {"min": 3, "max": 15},
    "Luteinizing hormone, serum Female follicular or luteal phase": {"min": 5, "max": 22},
    "Luteinizing hormone, serum Female midcycle peak": {"min": 30, "max": 250},
    "Luteinizing hormone, serum Female postmenopausal": {"min": 30},
    "Metanephrine, urine": {"max": 1.2},
    "Norepinephrine, plasma (supine)": {"min": 50, "max": 440},
    "Parathyroid hormone, serum": {"min": 10, "max": 65},
    "Progesterone, blood Male (adult)": {"min": 0.27, "max": 0.9},
    "Progesterone, blood Female follicular phase": {"min": 0.33, "max": 1.20},
    "Progesterone, blood Female luteal phase": {"min": 0.72, "max": 17.8},
    "Progesterone, blood Female postmenopausal": {"max": 1},
    "Progesterone, blood Female oral contraceptives": {"min": 0.34, "max": 0.92},
    "Prolactin, serum Male": {"max": 15},
    "Prolactin, serum Female": {"max": 20},
    "Testosterone, serum Male (adult)": {"min": 300, "max": 1200},
    "Testosterone, serum Female": {"min": 20, "max": 75},
    "Thyroid iodine (131I) uptake": {"min": 10, "max": 30},
    "Thyroid-stimulating hormone (TSH)": {"min": 0.5, "max": 5.0},
    "Thyroxine (T4), serum Total": {"min": 5, "max": 12},
    "Thyroxine (T4), serum Free": {"min": 0.9, "max": 2.4},
    "Triiodothyronine, free (T3)": {"min": 3.6, "max": 5.6},
    "Triiodothyronine, serum (T3)": {"min": 70, "max": 195},
    "Vanillylmandelic acid, urine": {"max": 8},
    "Catecholamines, 24-hour, urine": {"min":0, "max": 100},
    "Urine Albumin-creatinine ratio": {"min":0,"max": 30},
    "5-Hydroxyindoleacetic acid (5-HIAA)": {"min": 2, "max": 9},
    "Sodium, urine": {"min": 100, "max": 260},
    "Uric acid, urine": {"min": 250, "max": 750},
    "Gastrin, serum": {"max": 180},
    "Stool fat": {"min": 0, "max": 5},
    "Stool weight": {"min": 0, "max": 200},
    "Forced expiratory volume in 1 second (FEV1)": {"min": 80},
    "Forced vital capacity (FVC)": {"min": 80},
    "FEV1/FVC": {"min": 75},
    "Cerebrospinal Fluid Cell count": {"max": 5},
    "Cerebrospinal Fluid Glucose": {"min": 40, "max": 80},
    "Cerebrospinal Fluid Pressure (opening)": {"min": 70, "max": 200},
    "Cerebrospinal Fluid Protein": {"min": 15, "max": 60},
    "B type natriuretic peptide": {"max": 100},
    "5-Hydroxyindoleacetic acid (5-HIAA)": {"min": 2, "max": 9},
    "Urine Protein–creatinine ratio": {"min":0, "max": 0.2},
    "Left ventricular ejection fraction": {"min": 55},
    "Pulmonary artery Systolic": {"min": 20, "max": 25},
    "Pulmonary artery Diastolic": {"min": 5, "max": 10},
    "Pulmonary artery Mean": {"min": 9, "max": 16},
    "Pulmonary capillary wedge": {"min": 6, "max": 12},
    "Right atrium": {"min": 0, "max": 5},
    "Right ventricle Systolic": {"min": 20, "max": 25},
    "Right ventricle Diastolic": {"min":0, "max": 5}
}