AWS_RDS_HOST = 'new-mymedirecords.cbs8imeeg5j7.us-east-1.rds.amazonaws.com'
AWS_DB_NAME = "mymedirecords"
AWS_DB_USER_NAME = "postgres"
AWS_DB_PASS = "admin1234"
AWS_DB_PORT = 5432

AWS_access_key_id = "AKIAS3DOCB27QHMT5LBL"
AWS_secret_access_key = "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"
AWS_bucket_name = "mymedirecords"

OPEN_AI_API_KEY = "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"

REPORT_PATH = "data/reports"
EXTRACTED_PATH = "data/extracted_reports"

PersonalDetails = {"Name": "name", "ReportDate": "DD/MM/YYYY", "DoctorName": "doctor name", "Gender": "Male/Female"},

tests = {"Absolute neutrophil count": {"min": {"Male": 1780, "Female": 1560},
  "max": {"Male": 5380, "Female": 6130},
  "unit": "μL",
  "category": "Hematology"},
 "Activated partial thromboplastin time": {"min": 25,
  "max": 35,
  "unit": "s",
  "category": "Hematology"},
 "Bleeding time": {"min": 0,
  "max": 10,
  "unit": "min",
  "category": "Hematology"},
 "Erythrocyte count": {"min": 4.2,
  "max": 5.9,
  "unit": "x 10^6/μL",
  "category": "Hematology"},
 "Erythrocyte sedimentation rate": {"min": 0,
  "max": {"Male": 15, "Female": 20},
  "unit": "mm/h",
  "category": "Hematology"},
 "Erythropoietin": {"min": 0,
  "max": 30,
  "unit": "mU/mL",
  "category": "Hematology"},
 "D-Dimer": {"min": 0, "max": 0.5, "unit": "μg/mL", "category": "Hematology"},
 "Ferritin, serum": {"min": 15,
  "max": 200,
  "unit": "ng/mL",
  "category": "Iron studies"},
 "Haptoglobin, serum": {"min": 50,
  "max": 150,
  "unit": "mg/dL",
  "category": "Hematology"},
 "Hematocrit": {"min": {"Male": 41, "Female": 36},
  "max": {"Male": 51, "Female": 47},
  "unit": "%",
  "category": "Hematology"},
 "Hemoglobin, blood": {"min": {"Male": 14, "Female": 12},
  "max": {"Male": 17, "Female": 16},
  "unit": "g/dL",
  "category": "Hematology"},
 "Leukocyte count": {"min": 4000,
  "max": 10000,
  "unit": "μL",
  "category": "Hematology"},
 "Mean corpuscular volume": {"min": 80,
  "max": 100,
  "unit": "fL",
  "category": "Hematology"},
 "Platelet count": {"min": 150000,
  "max": 350000,
  "unit": "μL",
  "category": "Hematology"},
 "Prothrombin time": {"min": 11,
  "max": 13,
  "unit": "s",
  "category": "Hematology"},
 "Reticulocyte count": {"min": 0.5,
  "max": 1.5,
  "unit": "% of erythrocytes",
  "category": "Hematology"},
 "Protein, serum Total": {"min": 6.0,
  "max": 7.8,
  "unit": "g/dL",
  "category": "Kidney/Renal Function"},
 "Albumin": {"min": 3.5,
  "max": 5.5,
  "unit": "g/dL",
  "category": "Kidney/Renal Function"},
 "Globulins, total": {"min": 2.5,
  "max": 3.5,
  "unit": "g/dL",
  "category": "Immunoglobulins"},
 "Alkaline phosphatase, serum": {"min": 36,
  "max": 92,
  "unit": "units/L",
  "category": "Liver Biliary and Pancreas"},
 "Alpha-Fetoprotein, serum": {"min": 0,
  "max": 20,
  "unit": "ng/mL",
  "category": "Liver Biliary and Pancreas"},
 "Aminotransferase, alanine (ALT)": {"min": 0,
  "max": 35,
  "unit": "units/L",
  "category": "Liver Biliary and Pancreas"},
 "Aminotransferase, aspartate (AST)": {"min": 0,
  "max": 35,
  "unit": "units/L",
  "category": "Liver Biliary and Pancreas"},
 "Ammonia, plasma": {"min": 40,
  "max": 80,
  "unit": "μg/dL",
  "category": "Liver Biliary and Pancreas"},
 "Amylase, serum": {"min": 0,
  "max": 130,
  "unit": "units/L",
  "category": "Liver Biliary and Pancreas"},
 "Bicarbonate, serum": {"min": 23,
  "max": 28,
  "unit": "meq/L",
  "category": "Liver Biliary and Pancreas"},
 "Bilirubin, serum Total": {"min": 0.3,
  "max": 1.2,
  "unit": "mg/dL",
  "category": "Liver Biliary and Pancreas"},
 "Bilirubin, serum Direct": {"min": 0,
  "max": 0.3,
  "unit": "mg/dL",
  "category": "Liver Biliary and Pancreas"},
 "γ-Glutamyltransferase, serum": {"min": 0,
  "max": 30,
  "unit": "units/L",
  "category": "Liver Biliary and Pancreas"},
 "Fibrinogen, plasma": {"min": 150,
  "max": 350,
  "unit": "mg/dL",
  "category": "Hemat- Oncology"},
 "Lactic acid, venous blood": {"min": 6,
  "max": 16,
  "unit": "mg/dL",
  "category": "Hemat- Oncology"},
 "Lipase, serum": {"min": 0,
  "max": 95,
  "unit": "units/L",
  "category": "Hemat- Oncology"},
 "Magnesium, serum": {"min": 1.5,
  "max": 2.4,
  "unit": "mg/dL",
  "category": "Kidney/Renal Function"},
 "Tacrolimus level": {"min": 5,
  "max": 20,
  "unit": "mcg/L",
  "category": "Liver Biliary and Pancreas"},
 "Blood gases, arterial pH": {"min": 7.38,
  "max": 7.44,
  "unit": "",
  "category": "Liver Biliary and Pancreas"},
 "Pco2": {"min": 35,
  "max": 45,
  "unit": "mm Hg",
  "category": "Liver Biliary and Pancreas"},
 "Po2": {"min": 80,
  "max": 100,
  "unit": "mm Hg",
  "category": "Liver Biliary and Pancreas"},
 "Oxygen saturation": {"min": 95,
  "max": 100,
  "unit": "%",
  "category": "Liver Biliary and Pancreas"},
 "Blood urea nitrogen": {"min": 8,
  "max": 20,
  "unit": "mg/dL",
  "category": "Liver Biliary and Pancreas"},
 "C-reactive protein": {"min": 0,
  "max": 5,
  "unit": "mg/L",
  "category": "Rheumatology"},
 "Calcium, serum": {"min": 9,
  "max": 10.5,
  "unit": "mg/dL",
  "category": "Liver Biliary and Pancreas"},
 "Chloride, serum": {"min": 98,
  "max": 106,
  "unit": "meq/L",
  "category": "Liver Biliary and Pancreas"},
 "Cholesterol, plasma Total": {"min": 150,
  "max": 199,
  "unit": "mg/dL",
  "category": "Lipid Profile"},
 "LDL Cholesterol": {"min": 0,
  "max": 130,
  "unit": "mg/dL",
  "category": "Lipid Profile"},
 "HDL Cholesterol": {"min": 40,
  "max": 999,
  "unit": "mg/dL",
  "category": "Lipid Profile"},
 "Triglycerides": {"min": 0,
  "max": 150,
  "unit": "mg/dL",
  "category": "Lipid Profile"},
 "Complement C3": {"min": 55,
  "max": 120,
  "unit": "mg/dL",
  "category": "Hemat- Oncology"},
 "Complement Total (CH50)": {"min": 37,
  "max": 55,
  "unit": "U/mL",
  "category": "Hemat- Oncology"},
 "Creatine kinase, serum": {"min": 30,
  "max": 170,
  "unit": "units/L",
  "category": "Hemat- Oncology"},
 "Creatinine, serum": {"min": 0.7,
  "max": 1.3,
  "unit": "mg/dL",
  "category": "Hemat- Oncology"},
 "Sodium, serum": {"min": 136,
  "max": 145,
  "unit": "meq/L",
  "category": "Electrolytes"},
 "Potassium, serum": {"min": 3.5,
  "max": 5.0,
  "unit": "meq/L",
  "category": "Electrolytes"},
 "Chloride": {"min": 98,
  "max": 106,
  "unit": "meq/L",
  "category": "Electrolytes"},
 "Bicarbonate": {"min": 23,
  "max": 28,
  "unit": "meq/L",
  "category": "Electrolytes"},
 "Folate, red cell": {"min": 160,
  "max": 855,
  "unit": "ng/mL",
  "category": "Hemat- Oncology"},
 "Folate, serum": {"min": 2.5,
  "max": 20,
  "unit": "ng/mL",
  "category": "Hemat- Oncology"},
 "Glucose, plasma": {"min": 70,
  "max": 100,
  "unit": "mg/dL",
  "category": "Hemat- Oncology"},
 "Homocysteine, plasma": {"Male": {"min": 0.54, "max": 2.16},
  "Female": {"min": 0.41, "max": 1.89},
  "unit": "mg/L",
  "category": "Hemat- Oncology"},
 "IgG": {"min": 640,
  "max": 1430,
  "unit": "mg/dL",
  "category": "Immunoglobulins"},
 "IgA": {"min": 70,
  "max": 300,
  "unit": "mg/dL",
  "category": "Immunoglobulins"},
 "IgM": {"min": 20,
  "max": 140,
  "unit": "mg/dL",
  "category": "Immunoglobulins"},
 "IgD": {"min": 0, "max": 8, "unit": "mg/dL", "category": "Immunoglobulins"},
 "IgE": {"min": 0.01,
  "max": 0.04,
  "unit": "mg/dL",
  "category": "Immunoglobulins"},
 "Iron, serum": {"min": 60,
  "max": 160,
  "unit": "μg/dL",
  "category": "Iron studies"},
 "Iron-binding capacity, total, serum": {"min": 250,
  "max": 460,
  "unit": "μg/dL",
  "category": "Iron studies"},
 "Transferrin saturation": {"min": 20,
  "max": 50,
  "unit": "%",
  "category": "Iron studies"},
 "Lactate dehydrogenase, serum": {"min": 60,
  "max": 100,
  "unit": "units/L",
  "category": "Hemat- Oncology"},
 "Methylmalonic acid, serum": {"min": 150,
  "max": 370,
  "unit": "nmol/L",
  "category": "Hemat- Oncology"},
 "Osmolality, plasma": {"min": 275,
  "max": 295,
  "unit": "mosm/kg H2O",
  "category": "Kidney/Renal Function"},
 "Phosphatase, alkaline, serum": {"min": 36,
  "max": 92,
  "unit": "units/L",
  "category": "Kidney/Renal Function"},
 "Phosphorus, serum": {"min": 3,
  "max": 4.5,
  "unit": "mg/dL",
  "category": "Kidney/Renal Function"},
 "Prostate-specific antigen, serum": {"min": 0,
  "max": 4,
  "unit": "ng/mL",
  "category": "Kidney/Renal Function"},
 "Rheumatoid factor": {"min": 0,
  "max": 25,
  "unit": "IU/ml",
  "category": "Rheumatology"},
 "Troponin I": {"min": 0,
  "max": 0.5,
  "unit": "ng/mL",
  "category": "Cardiology"},
 "Troponin T": {"min": 0,
  "max": 0.1,
  "unit": "ng/mL",
  "category": "Cardiology"},
 "Creatine kinase": {"min": 25,
  "max": 200,
  "unit": "U/L",
  "category": "Cardiology"},
 "Creatine kinase MB (CKMB)": {"min": 0,
  "max": 4,
  "unit": "ng",
  "category": "Cardiology"},
 "B type natriuretic peptide": {"min": 0,
  "max": 100,
  "unit": "pg/ml",
  "category": "Cardiology"},
 "Urea nitrogen, blood": {"min": 8,
  "max": 20,
  "unit": "mg/dL",
  "category": "Kidney/Renal Function"},
 "Uric acid, serum": {"min": 2.5,
  "max": 8,
  "unit": "mg/dL",
  "category": "Kidney/Renal Function"},
 "Vitamin B12, serum": {"min": 200,
  "max": 800,
  "unit": "pg/mL",
  "category": "Hemat- Oncology"},
 "Adrenocorticotropic hormone (ACTH), serum": {"min": 9,
  "max": 52,
  "unit": "pg/mL",
  "category": "Endocrine"},
 "Aldosterone, serum Supine": {"min": 2,
  "max": 5,
  "unit": "ng/dL",
  "category": "Endocrine"},
 "Aldosterone, serum Standing": {"min": 7,
  "max": 20,
  "unit": "ng/dL",
  "category": "Endocrine"},
 "Aldosterone, urine": {"min": 5,
  "max": 19,
  "unit": "μg/24 h",
  "category": "Endocrine"},
 "Epinephrine, plasma (supine)": {"min": 0,
  "max": 75,
  "unit": "ng/L",
  "category": "Endocrine"},
 "Norepinephrine, plasma (supine)": {"min": 50,
  "max": 440,
  "unit": "ng/L",
  "category": "Endocrine"},
 "Catecholamines, 24-hour, urine": {"min": 0,
  "max": 100,
  "unit": "μg/m2 per 24 h",
  "category": "Endocrine"},
 "Cortisol, free, urine": {"min": 0,
  "max": 50,
  "unit": "μg/24 h",
  "category": "Endocrine"},
 "Dehydroepiandrosterone sulfate (DHEA), plasma": {"Male": {"min": 1.3,
   "max": 5.5},
  "Female": {"min": 0.6, "max": 3.3},
  "unit": "μg/mL",
  "category": "Endocrine"},
 "Estradiol, serum": {"Male": {"min": 10, "max": 30},
  "Female": {"min": 14, "max": 54},
  "unit": "pg/mL",
  "category": "Endocrine"},
 "Follicle-stimulating hormone, serum": {"Male": {"min": 5, "max": 15},
  "Female": {"min": 5, "max": 50},
  "unit": "mU/mL",
  "category": "Endocrine"},
 "Growth hormone, plasma": {"min": 0,
  "max": 7,
  "unit": "ng/mL",
  "category": "Endocrine"},
 "Luteinizing hormone, serum": {"Male": {"min": 3, "max": 15},
  "Female": {"min": 5, "max": 250},
  "unit": "mU/mL",
  "category": "Endocrine"},
 "Metanephrine, urine": {"min": 0,
  "max": 1.2,
  "unit": "mg/24 h",
  "category": "Endocrine"},
 "Parathyroid hormone, serum": {"min": 10,
  "max": 65,
  "unit": "pg/mL",
  "category": "Endocrine"},
 "Progesterone, blood": {"Male": {"min": 0.27, "max": 0.9},
  "Female": {"min": 0.33, "max": 17.8},
  "unit": "ng/mL",
  "category": "Endocrine"},
 "Prolactin, serum": {"Male": {"min": 0, "max": 15},
  "Female": {"min": 0, "max": 20},
  "unit": "ng/mL",
  "category": "Endocrine"},
 "Testosterone, serum": {"Male": {"min": 300, "max": 1200},
  "Female": {"min": 20, "max": 75},
  "unit": "ng/dL",
  "category": "Endocrine"},
 "Thyroid stimulating hormone (TSH)": {"min": 0.5,
  "max": 5.0,
  "unit": "μU/mL",
  "category": "Endocrine"},
 "Thyroxine (T4), serum Total": {"min": 5,
  "max": 12,
  "unit": "μg/dL",
  "category": "Endocrine"},
 "Free T4": {"min": 0.9, "max": 2.4, "unit": "ng/dL", "category": "Endocrine"},
 "Triiodothyronine, free (T3)": {"min": 3.6,
  "max": 5.6,
  "unit": "ng/L",
  "category": "Endocrine"},
 "Triiodothyronine, serum (T3)": {"min": 70,
  "max": 195,
  "unit": "ng/dL",
  "category": "Endocrine"},
 "Vanillylmandelic acid, urine": {"min": 0,
  "max": 8,
  "unit": "mg/24 h",
  "category": "Endocrine"},
 "Vitamin D 1,25-dihydroxy, serum": {"min": 25,
  "max": 65,
  "unit": "pg/mL",
  "category": "Endocrine"},
 "Vitamin D 25-hydroxy, serum": {"min": 25,
  "max": 80,
  "unit": "ng/mL",
  "category": "Endocrine"},
 "Glomerular filtration rate (GFR) Normal": {"Male": {"min": 130, "max": 999},
  "Female": {"min": 120, "max": 999},
  "unit": "mL/min/1.73 m2",
  "category": "Kidney/Renal Function"},
 "Stages of Chronic Kidney Disease": {"min": 90, "max": 999,
  "unit": "mL/min/1.73 m2",
  "category": "Kidney/Renal Function"},
 "5-Hydroxyindoleacetic acid (5-HIAA)": {"min": 2,
  "max": 9,
  "unit": "mg/24 h",
  "category": "Kidney/Renal Function"},
 "Urine Protein–creatinine ratio": {"min": 0,
  "max": 0.2,
  "unit": "mg/mg",
  "category": "Kidney/Renal Function"},
 "Urine Albumin-creatinine ratio": {"min": 0,
  "max": 30,
  "unit": "mg/g",
  "category": "Kidney/Renal Function"},
 "Urine Sodium": {"min": 100,
  "max": 260,
  "unit": "meq/24 h",
  "category": "Kidney/Renal Function"},
 "Urine Uric acid": {"min": 250,
  "max": 750,
  "unit": "mg/24 h",
  "category": "Kidney/Renal Function"},
 "Gastrin, serum": {"min": 0,
  "max": 180,
  "unit": "pg/mL",
  "category": "Gastrointestinal"},
 "Stool fat": {"min": 0,
  "max": 5,
  "unit": "g/d",
  "category": "Gastrointestinal"},
 "Stool weight": {"min": 0,
  "max": 200,
  "unit": "g/d",
  "category": "Gastrointestinal"},
 "Forced expiratory volume in 1 second (FEV1)": {"min": 80,
  "max": 999,
  "unit": "% of predicted",
  "category": "Pulmonary"},
 "Forced vital capacity (FVC)": {"min": 80,
  "max": 999,
  "unit": "% of predicted",
  "category": "Pulmonary"},
 "FEV1/FVC": {"min": 75, "max": 999, "unit": "%", "category": "Pulmonary"},
 "Cerebrospinal Fluid Cell count": {"min": 0,
  "max": 5,
  "unit": "/μL",
  "category": "Neurology"},
 "Cerebrospinal Fluid Glucose": {"min": 40,
  "max": 80,
  "unit": "mg/dL",
  "category": "Neurology"},
 "Cerebrospinal Fluid Pressure (opening)": {"min": 70,
  "max": 200,
  "unit": "mm H2O",
  "category": "Neurology"},
 "Cerebrospinal Fluid Protein": {"min": 15,
  "max": 60,
  "unit": "mg/dL",
  "category": "Neurology"},
 "Alpha fetoprotein": {"min": 0,
  "max": 20,
  "unit": "ng/mL",
  "category": "Tumor markers /Oncology"},
 "Beta human chorionic gonadotropin (HCG)": {"min": 0,
  "max": 5,
  "unit": "IU/I",
  "category": "Tumor markers /Oncology"},
 "CA19.9": {"min": 0,
  "max": 40,
  "unit": "U/mL",
  "category": "Tumor markers /Oncology"},
 "Carcinoembryonic antigen (CEA)": {"min": 0,
  "max": 4,
  "unit": "ug/L",
  "category": "Tumor markers /Oncology"},
 "Prostatic acid phosphatase (PAP)": {"min": 0,
  "max": 3,
  "unit": "U/dL",
  "category": "Tumor markers /Oncology"},
 "Prostate-specific antigen (PSA)": {"min": 0,
  "max": 4,
  "unit": "ug/L",
  "category": "Tumor markers /Oncology"},
 "Alpha 1-antitrypsin": {"min": 20,
  "max": 50,
  "unit": "µmol/L",
  "category": "Rheumatology"},
 "Angiotensin-converting enzyme": {"min": 23,
  "max": 57,
  "unit": "U/L",
  "category": "Rheumatology"},
 "D-dimer": {"min": 0,
  "max": 500,
  "unit": "ng/mL",
  "category": "Rheumatology"},
 "Erythrocyte sedimentation rate (ESR)": {"min": 0,
  "max": 10,
  "unit": "mm/hour",
  "category": "Rheumatology"},
 "Lactate dehydrogenase (LDH)": {"min": 50,
  "max": 150,
  "unit": "U/L",
  "category": "Rheumatology"},
 "Lead": {"min": 0, "max": 40, "unit": "µg/dL", "category": "Rheumatology"},
 "Cardiac index": {"min": 2.5,
  "max": 4.2,
  "unit": "L/min/m2",
  "category": "Hemodynamic Measurements"},
 "Left ventricular ejection fraction": {"min": 55,
  "max": 100,
  "unit": "%",
  "category": "Hemodynamic Measurements"},
 "Pulmonary artery systolic": {"min": 20,
  "max": 25,
  "unit": "mm Hg",
  "category": "Hemodynamic Measurements"},
 "Pulmonary artery diastolic": {"min": 5,
  "max": 10,
  "unit": "mm Hg",
  "category": "Hemodynamic Measurements"},
 "Pulmonary artery mean": {"min": 9,
  "max": 16,
  "unit": "mm Hg",
  "category": "Hemodynamic Measurements"},
 "Pulmonary capillary wedge": {"min": 6,
  "max": 12,
  "unit": "mm Hg",
  "category": "Hemodynamic Measurements"},
 "Right atrium mean": {"min": 0,
  "max": 5,
  "unit": "mm Hg",
  "category": "Hemodynamic Measurements"},
 "Right ventricle systolic": {"min": 20,
  "max": 25,
  "unit": "mm Hg",
  "category": "Hemodynamic Measurements"},
 "Right ventricle diastolic": {"min": 0,
  "max": 5,
  "unit": "mm Hg",
  "category": "Hemodynamic Measurements"},
  "Glycosylated Hb": {"min": 0,
  "max": 10,
  "unit": "mm Hg",
  "category": "Hemodynamic Measurements"} }